spring.datasource.url=jdbc:postgresql://localhost:5433/westlakersdb
spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=none
spring.datasource.username=postgres
spring.datasource.password=<change-me>
spring.security.user.name=devuser
spring.security.user.password=<change-me>
