spring.datasource.url=jdbc:postgresql://localhost:5433/westlakersdb
spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=none
spring.datasource.username=postgres
spring.datasource.password=<change-me>
spring.security.user.name=devuser
spring.security.user.password=<change-me>

spring.data.redis.host=localhost
spring.data.redis.port=8100
spring.data.redis.timeout=20000ms
spring.data.redis.jedis.pool.max-active=8
spring.data.redis.jedis.pool.max-idle=8
spring.data.redis.jedis.pool.min-idle=0
spring.data.redis.jedis.pool.max-wait=-1ms