spring.config.import=optional:file:./application-dev-local.properties,optional:file:./config/application-dev-local.properties

spring.datasource.url=jdbc:postgresql://localhost:5433/westlakersdb
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false




